version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: '8061'
    ports:
      - '8061:8061'
    restart: 'no'

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    environment:
      SERVER_HOST: "server"
      SERVER_PORT: '8061'
    restart: 'no'
    depends_on:
      - server
